# Generated by Django 3.2.4 on 2021-06-05 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratemymovie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='people',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='ratemymovie.movie'),
        ),
        migrations.AlterField(
            model_name='people',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
