# Generated by Django 3.2.4 on 2021-06-06 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemymovie', '0003_rename_movie_id_people_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
