# Generated by Django 3.2.4 on 2021-06-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratemymovie', '0004_alter_people_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='PeopleRating',
        ),
    ]
